# 関数と変数に同じ名前をつけてはならない

## こういうことになる

```python
def function(arg):
    return arg

result = function('OK')
print(result)
# => OK

function = function('OK?')
print(function)
# => OK?

result2 = function('Check')
# => TypeError: 'str' object is not callable
```

## どうしてそうなる？

Pythonのドキュメントの[関数定義](https://docs.python.org/ja/3/reference/compound_stmts.html#function-definitions) によると、

> 関数定義を実行すると、現在のローカルな名前空間内で関数名を関数オブジェクト (関数の実行可能コードをくるむラッパー) に束縛します。

とのことなので、上記コードの `function = function('OK?')` 部分で `function` という名前の束縛を変更してしまったものと思われます。

以下、確認

```python
def function(arg):
    return arg
print(function)
# => <function function at 0x14b65abdc1f0>

function = 'OK?'
print(function)
# => OK?
```

元々、関数オブジェクトを指していた 'function' が、代入によって文字列に上書きされたことが確認できた。

## ということは？

逆もまた然り

```python
variable = 'variable'
print(variable)
# => variable

def variable(arg):
    pass
print(variable)
# => <function variable at 0x147c19aef1f0>
```

